name: lambda deployment

on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:


  
  build:
    runs-on: ubuntu-latest
    environment: ${{ steps.branch_check.outputs.env_name }}
    steps:
    - name: Some check on branch
      id: branch_check
      run: |
        echo "Running on branch ${{ github.ref }}"
        if [ "${{ github.ref }}" = "refs/heads/main" ]; then
          echo "::set-output name=env_name::main"
        elif [ "${{ github.ref }}" = "refs/heads/dev" ]; then
          echo "::set-output name=env_name::dev"
        else
           echo "::set-output name=env_name::feature"
        fi               
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install awscliv2

    - name: zip lambda
      run: | 
        cd lambda_function
        mkdir package
        pip install --target ./package requests
        pip install --target ./package -r requirements.txt
        cd package
        zip -r ../dep-package.zip .
        cd ..
        zip dep-package.zip lambda.py

    - uses: hkusu/s3-upload-action@v2
      id: upload # specify some ID for use in subsequent steps
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: 'us-east-1'
        aws-bucket: amy-powerbi
        file-path: './lambda_function/dep-package.zip'
        output-qr-url: 'true' # specify true
    - name: Show URL
      run: echo '${{ steps.upload.outputs.qr-url }}' # use this output
  
    - name: upload zip 
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_ACCESS_KEY_SECRET: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      run: |
        aws s3 cp lambda_function/dep-package.zip s3://amy-powerbi/dep-package.zip --region us-east-1 
#     - run: aws s3 sync builddir s3://amy-powerbi --region us-east-1 --cache-control max-age=0 --acl public-read --delete

